FROM python:3.12.11-slim

WORKDIR /monitoring_service


COPY requirements/req_monitoring.txt ./
RUN pip install --no-cache-dir -r req_monitoring.txt


COPY ./monitoring_service ./
CMD [ "python", "monitoring.py" ] 