FROM python:3.12.11-slim

WORKDIR /monitoring_service
RUN groupadd --gid 2000 node && useradd --uid 2000 --gid node --shell /bin/bash --create-home node

COPY requirements/req_monitoring.txt ./
RUN pip install --no-cache-dir -r req_monitoring.txt

USER node

COPY --chown=node:node ./monitoring_service ./
CMD [ "python", "monitoring.py" ] 