FROM python:3.12.11-slim

WORKDIR /service_analitics

USER appuser
COPY requirements/req_analitics_service.txt ./
RUN pip install --no-cache-dir -r req_analitics_service.txt


COPY ./service_analitics/ ./
CMD [ "python", "start_analitics_service.py" ]