FROM python:3.12.11-slim

WORKDIR /service_analitics
RUN groupadd --gid 2000 node && useradd --uid 2000 --gid node --shell /bin/bash --create-home node

COPY requirements/req_analitics_service.txt ./
RUN pip install --no-cache-dir -r req_analitics_service.txt

USER node

COPY --chown=node:node ./service_analitics/ ./
CMD [ "python", "start_analitics_service.py" ]