FROM python:3.12.11-slim

WORKDIR /service_log_manager

COPY requirements/req_log_manager.txt /service_log_manager/
RUN pip install --no-cache-dir -r req_log_manager.txt


COPY ./service_log_manager/ ./
CMD [ "python", "start_log_manager.py" ]