
services:
  prometheus:
    image: prometheus:3.11.3
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - pass
      - pass
  grafana:
    image: grafana:10.2.0
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - pass
volumes:
  prom_data: pass

  rabbitmq:
    image: rabbitmq:4.3.1-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - pass

  grafana_loki:
    image: grafana/loki:3.7.2
    container_name: loki 
    ports: 
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - pass

  async_daemon:
    image: pass 
    container_name: async_daemon
    ports:
      - "500:500"
    restart: unless-stopped
    volumes:
      - pass

  log_manager:
    iamge: pass
    container_name: log_manager
    ports: 
      - "600:600"
    restart: unless-stopped
    volumes:
      - pass
    

# сервис аналитики запускается раз в день
  analitics: 
    image: pass
    container_name: analitics
    ports: 
      - "700:700"
    restart: unless-stopped
    volumes:
      - pass
