
services:
  prometheus:
    image:  prom/prometheus:v3.11.3
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
  grafana:
    image:  grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
  rabbitmq:
    image: rabbitmq:4.3.1-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:var/lib/rabbitmq

  grafana_loki:
    image: grafana/loki:3.7.2
    container_name: grafana_loki 
    ports: 
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - loki_data/loki

  async_daemon:
    build: 
      context: .
      dockerfile: Docker/Dockerfile.monitoring_service
    image: monitoring_service:latest
    container_name: async_daemon
    ports:
      - "8001:8001"
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
      grafana:
        condition: service_started
    volumes:
      - ./config.json:/monitoring_service/config.json:ro

  log_manager:
    build: 
      context: .
      dockerfile: Docker/Dockerfile.log_manager
    image: log_manager:latest
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_started
      grafana_loki:
        condition: service_started
      grafana:
        condition: service_started
    volumes: 
      - ./config.json:/service_log_manager/config.json:ro

# сервис аналитики запускается раз в день
  analitics:
    build:
      context: .
      dockerfile: Docker/Dockerfile.analitics
    image: analitics:latest
    container_name: analitics
    restart: "no"
  
  app:
    build: 
      context: .
      dockerfile: Docker/Dockerfile.app
    image: app:latest
    container_name: app
    restart: unless-stopped
    ports: 
      - "8000:8000"

volumes:
  prom_data: 
  grafana_data:
  rabbitmq_data:
  loki_data: